export interface MemberShip {
  memberID: number;
  userName: string;
  pwd: string;
  userLevelID: number;
  mGroupID: number;
  birthday: string | null;
  moneyPwd: string;
  nickName: string;
  fullName: string;
  agentParentID: number;
  agentPositionTakingRebate: string;
  agentParentMap: string;
  agentLevelSCID: number | null;
  referralParentID: number;
  referralPayType: number | null;
  referralLayerLevel: string;
  referralMap: string;
  referralCashRebate: string;
  email: string;
  phone: string;
  loginTime: string | null;
  lastLoginTime: string | null;
  loginIP: string;
  totalBalance: string;
  monthDeposit: string;
  totalDeposit: string;
  maxWinAmount: string;
  totalRealBet: string;
  referralLink: string;
  userType: string;
  isMultiLogin: boolean;
  walletIsLock: boolean;
  firstPwd: string;
  secondPwd: string;
  cashRebatePayType: number | null;
  cashBackRebatePayType: number | null;
  isEditPhone: boolean;
  isEmailValidator: boolean;
  isEditEmail: boolean;
  isFirst: boolean;
  isLock: boolean;
  isEnable: boolean;
  isOnline: boolean;
  createBy: number;
  createDate: string;
  updateBy: number;
  updateDate: string;
}
